"use client";

import Link from "next/link";
import { useState } from "react";
import { ArrowRight, Check, ExternalLink } from "lucide-react";

type Section = "operating" | "strategies" | "offer" | "sales" | "delivery";

const strategies = [
  ["1", "Private sample outbound", "Primary", "One private proof clip for fit-ranked prospects, then two more clips only after interest."],
  ["2", "Audit-first outbound", "Capacity release", "Send the missed moment and funnel diagnosis first; edit only for prospects who reply."],
  ["3", "Authority content", "Trust layer", "Publish one technically accurate Energy Dial explainer weekly. Support outbound; do not wait for inbound."],
  ["4", "Producer partnerships", "Leverage", "White-label for podcast producers, newsletters, and event teams that already serve several experts."],
  ["5", "Focused hybrid", "90-day recommendation", "70% private-sample outbound, 20% authority proof, 10% partner conversations."],
];

const sources = [
  ["Offers", "Value equation, offer stacking, risk reversal", "https://www.acquisition.com/offers-oo"],
  ["Leads", "Cold one-to-one is the first-client engine", "https://www.acquisition.com/leads-oo"],
  ["Money Models", "Attraction, upsell, downsell, continuity", "https://www.acquisition.com/mm-oo"],
];

function Frame({ title, children }: { title: string; children: React.ReactNode }) {
  return <section className="rounded-md border border-zinc-200 bg-white p-5"><h3 className="text-base font-black text-zinc-950">{title}</h3><div className="mt-4">{children}</div></section>;
}

function Operating() {
  const math = [["Weekly time", "25h"], ["Solo paid ceiling", "5 clients"], ["Monthly clips at ceiling", "20"], ["Founding MRR at ceiling", "$4,985"]];
  return <div className="grid gap-5"><div className="grid grid-cols-2 gap-px overflow-hidden rounded-md border border-zinc-200 bg-zinc-200 lg:grid-cols-4">{math.map(([label, value]) => <div key={label} className="bg-white p-4"><div className="text-2xl font-black text-brand-blue">{value}</div><div className="mt-1 text-[10px] font-extrabold uppercase text-zinc-500">{label}</div></div>)}</div><div className="grid gap-5 lg:grid-cols-2"><Frame title="Weekly allocation"><ul className="space-y-2 text-sm leading-6 text-zinc-700">{["25 new qualified contacts", "15 follow-ups", "Two private samples", "One Energy Dial authority clip", "One pipeline and delivery review"].map(x=><li key={x} className="flex gap-2"><Check size={15} className="mt-1 shrink-0 text-brand-orange" />{x}</li>)}</ul></Frame><Frame title="Decision thresholds"><ul className="space-y-2 text-sm leading-6 text-zinc-700">{["<3 replies from 30: fix targeting/message", "Replies but <2 trials: fix proof/trial framing", "3 completed trials and no close: inspect offer and sales before price", "At client 3: document and test contractor workflow", "Before client 6: add fulfillment capacity"].map(x=><li key={x} className="border-b border-zinc-100 pb-2 last:border-0">{x}</li>)}</ul></Frame></div><Frame title="First-client funnel"><div className="grid gap-2 sm:grid-cols-5">{[["100","ranked"],["40","qualified"],["30","contacted"],["4-5","trial talks"],["1","client"]].map(([v,l],i)=><div key={l} className="relative rounded-md bg-zinc-50 p-3"><div className="text-xl font-black text-brand-orange">{v}</div><div className="text-[10px] font-bold uppercase text-zinc-500">{l}</div>{i<4&&<ArrowRight size={14} className="absolute -right-2 top-5 hidden text-brand-blue sm:block" />}</div>)}</div><p className="mt-3 text-xs leading-5 text-zinc-500">Planning assumptions, not market benchmarks. Replace them with DialDash outcomes after every 30 qualified contacts.</p></Frame></div>;
}

function Strategies() { return <div className="grid gap-3">{strategies.map(([n,title,role,detail])=><div key={n} className="grid gap-3 rounded-md border border-zinc-200 bg-white p-4 sm:grid-cols-[38px_220px_1fr]"><span className="flex h-8 w-8 items-center justify-center rounded bg-brand-blue text-xs font-black text-white">{n}</span><div><div className="font-black">{title}</div><div className="mt-1 text-[10px] font-bold uppercase text-brand-orange">{role}</div></div><p className="text-sm leading-6 text-zinc-600">{detail}</p></div>)}</div>; }

function Offer() { return <div className="grid gap-5 lg:grid-cols-2"><Frame title="$997 founding package"><ul className="space-y-2 text-sm leading-6 text-zinc-700">{["Four educational clips per month", "One nominated source episode per week", "Selection rationale and technical accuracy pass", "Motion edit, clean select, thumbnail direction", "Posting title/caption/CTA pack", "One consolidated revision round"].map(x=><li key={x} className="flex gap-2"><Check size={15} className="mt-1 text-brand-orange" />{x}</li>)}</ul></Frame><Frame title="Three-clip trial"><ol className="space-y-3 text-sm leading-6 text-zinc-700">{["One private unsolicited sample for only the best prospects", "Two additional clips after they accept the trial", "Seven-day or one-episode boundary", "Ask for portfolio permission after approval", "Convert with scope and Flutterwave link"].map((x,i)=><li key={x} className="grid grid-cols-[20px_1fr]"><span className="font-black text-brand-orange">{i+1}.</span>{x}</li>)}</ol></Frame><Frame title="Bonuses that remove real friction"><div className="grid gap-2 text-sm text-zinc-700">{["Opportunity Map: three ranked clip moments", "Posting Pack: title, caption, CTA, source link", "Evidence Pack: maps, data, terminology sources", "Clean Select Library: reusable private archive", "Monthly Distribution Review: learning and next tests"].map(x=><div key={x} className="rounded bg-zinc-50 p-3">{x}</div>)}</div></Frame><Frame title="Price discipline"><p className="text-sm leading-6 text-zinc-700">Keep $997 through at least 30 qualified conversations or five completed trials. If a qualified buyer wants the outcome but cannot approve the amount, reduce scope to two clips; do not sell the same package for $297.</p><div className="mt-4 rounded-md border border-brand-orange/25 bg-brand-orange/5 p-3 text-xs font-bold text-[#a84e00]">No views or revenue guarantee. Guarantee one controlled revision against the agreed brief.</div></Frame></div>; }

function Sales() { return <div className="grid gap-5 lg:grid-cols-2"><Frame title="DM"><p className="whitespace-pre-wrap text-sm leading-6 text-zinc-700">[Name] - the point you made in [episode] about [idea] would work unusually well as a visual explainer. I made a private 30-second version using [map/diagram/number] so it stays technically accurate rather than becoming a rapid-cut clip. [link]{"\n\n"}I am a petroleum engineer building Energy Dial. If the direction is useful, I will make two more clips from the episode free. If it is not, no problem.</p></Frame><Frame title="Trial-to-paid close"><p className="text-sm leading-6 text-zinc-700">Which of the three directions best represents how you want the show to look? If you want this handled weekly, the founding package is four clips per month for $997. I can send the one-page scope and Flutterwave link now, or we can use 15 minutes to settle workflow and approvals.</p></Frame><Frame title="Follow-up sequence"><ol className="space-y-2 text-sm leading-6 text-zinc-700">{["Day 0: private sample DM", "Day 2-3: email referencing the same sample", "Day 7: one useful observation or archive angle", "Day 14: close the loop; move to nurture", "Do not hit every channel on the same day"].map((x,i)=><li key={x}><span className="mr-2 font-black text-brand-orange">{i+1}.</span>{x}</li>)}</ol></Frame><Frame title="Proof without claiming your result"><p className="text-sm leading-6 text-zinc-700">Use Schneider Electric, AGL, ACCIONA, and Shell platform case studies as evidence that expert-led video can reach professional energy audiences. Label them third-party cases. They do not prove Energy Dial will reproduce the result.</p></Frame></div>; }

function Delivery() { return <div className="grid gap-5 lg:grid-cols-2"><Frame title="Manual-first stack"><ul className="space-y-2 text-sm leading-6 text-zinc-700">{["Google Drive: source and finished media", "DialDash portal: status, versions, feedback, approval", "Flutterwave: hosted payment link", "Manual synchronization for first three clients", "Supabase later: auth and metadata, not primary video storage"].map(x=><li key={x} className="flex gap-2"><Check size={15} className="mt-1 text-brand-orange" />{x}</li>)}</ul><Link href="/portal/demo" className="mt-5 inline-flex items-center gap-2 rounded-md bg-brand-blue px-4 py-2.5 text-sm font-extrabold text-white">Open client portal preview<ArrowRight size={15} /></Link></Frame><Frame title="Retention system"><ol className="space-y-3 text-sm leading-6 text-zinc-700">{["Welcome and confirm owners/workflow inside 48 hours", "Get the first paid clip approved and posted inside seven days", "Track delivery, revisions, publishing, and business-relevant responses", "Run a short monthly distribution review", "Ascend to long-form only after a fixed-scope paid pilot"].map((x,i)=><li key={x} className="grid grid-cols-[22px_1fr]"><span className="font-black text-brand-orange">{i+1}.</span>{x}</li>)}</ol></Frame><Frame title="Source grounding"><div className="grid gap-2">{sources.map(([name,detail,url])=><a key={name} href={url} target="_blank" rel="noreferrer" className="flex items-start justify-between gap-3 rounded bg-zinc-50 p-3"><span><span className="block text-sm font-black">{name}</span><span className="mt-1 block text-xs text-zinc-500">{detail}</span></span><ExternalLink size={13} className="text-brand-blue" /></a>)}</div></Frame><Frame title="Full operating document"><p className="text-sm leading-6 text-zinc-700">The detailed source ledger, capacity math, scripts, thresholds, proof caveats, and five plans are maintained in <code className="rounded bg-zinc-100 px-1 py-0.5 text-xs">docs/ACQUISITION_OPERATING_MODEL.md</code>.</p></Frame></div>; }

export function AcquisitionPlaybook() {
  const [section, setSection] = useState<Section>("operating");
  const tabs: Array<[Section,string]> = [["operating","Operating math"],["strategies","5 strategies"],["offer","Offer"],["sales","Sales"],["delivery","Delivery & LTV"]];
  return <div className="rounded-lg border border-zinc-200 bg-[#f6f7f9] shadow-sm"><div className="border-b border-zinc-200 bg-white px-5 py-7 lg:px-8"><div className="text-xs font-extrabold uppercase tracking-[0.14em] text-brand-blue">First-client operating system</div><h2 className="mt-2 text-3xl font-black">From zero proof to retained revenue</h2><p className="mt-3 max-w-4xl text-base leading-7 text-zinc-600">Fit-ranked outbound creates proof. A narrow offer converts it. Fast activation, measured delivery, and capacity discipline keep it.</p><nav className="mt-6 flex gap-1 overflow-x-auto rounded-md border border-zinc-200 bg-zinc-50 p-1" aria-label="Playbook sections">{tabs.map(([id,label])=><button key={id} type="button" onClick={()=>setSection(id)} className={`whitespace-nowrap rounded px-3 py-2 text-xs font-extrabold ${section===id?"bg-white text-brand-blue shadow-sm":"text-zinc-500 hover:text-zinc-900"}`}>{label}</button>)}</nav></div><div className="p-4 sm:p-5 lg:p-7">{section==="operating"&&<Operating/>}{section==="strategies"&&<Strategies/>}{section==="offer"&&<Offer/>}{section==="sales"&&<Sales/>}{section==="delivery"&&<Delivery/>}</div></div>;
}
